apiVersion: "security.cloud.ibm.com/v1"
kind:       JwtConfig
metadata:
  name:      samplejwtconfig
  namespace: sample-app
spec:
  jwksUrl: https://eu-gb.appid.test.cloud.ibm.com/oauth/v4/<<Tenant Id>>/publickeys
