apiVersion: "security.cloud.ibm.com/v1"
kind:       OidcConfig
metadata:
  name:      oidc-provider-config-with-secret-ref
  namespace: sample-app
spec:
  authMethod:   client_secret_basic
  discoveryUrl: https://us-south.appid.cloud.ibm.com/oauth/v4/<tenant-ID>/oidc-discovery/.well-known
  clientId:     <client-id>
  clientSecretRef:
    name:  oidc-config-secret 	# <name-of-my-kube-secret>
    key:   secret 				# <key-in-my-kube-secret>
