apiVersion: "security.cloud.ibm.com/v1"
kind:       OidcConfig
metadata:
  name:      sampleoidcconfigwithsecretref
  namespace: sample-app
spec:
  authMethod:   client_secret_basic
  clientId:     clientId
  discoveryUrl: https://us-south.appid.cloud.ibm.com/oauth/v4/a9d75222-f70c-4ad3-97a5-60fdfde4df9f/.well-known/openid-configuration
  clientSecretRef:
    name:   oidcconfigsecret
    key:    secret
